using System.Text;

namespace GoodRpc.SourceGen;

internal static class Emitter
{
    public static string Generate(RpcInterfaceModel model)
    {
        var sb = new StringBuilder();
        sb.Append(Header);

        AppendProxy(sb, model);
        sb.AppendLine();
        AppendDispatcher(sb, model);
        sb.AppendLine();
        AppendRegistration(sb, model);

        return sb.ToString();
    }

    static void Append(StringBuilder sb, string text) => sb.Append(text);

    static void AppendLine(StringBuilder sb, string text = "") => sb.AppendLine(text);

    static string StripI(string name) =>
        name.StartsWith("I") && name.Length > 1 && char.IsUpper(name[1]) ? name.Substring(1) : name;

    static readonly string Header = $$"""
// <auto-generated/>
#pragma warning disable

using System.Buffers;
using System.Runtime.CompilerServices;
using System.Threading;
using System.Threading.Tasks;
using MemoryPack;
using GoodRpc;

""";

    // ── Proxy ─────────────────────────────────────────────────

    static void AppendProxy(StringBuilder sb, RpcInterfaceModel model)
    {
        var pn = StripI(model.Name) + "Proxy";
        var iface = model.FullyQualifiedName;

        AppendLine(
            sb,
            $$"""
file sealed class {{pn}} : RpcProxyBase, {{iface}}
{
    public {{pn}}(RpcTransport transport, PeerId peer) : base(transport, peer) { }
"""
        );

        foreach (var m in model.Methods)
        {
            AppendLine(sb);
            AppendProxyMethod(sb, m);
        }

        AppendLine(sb, "}");
    }

    static void AppendProxyMethod(StringBuilder sb, RpcMethodModel m)
    {
        var opts =
            $"new RpcSendOptions(Channel:{m.Channel},Delivery:(DeliveryType){m.Delivery},TimeoutMs:{m.TimeoutMs},Compress:{m.Compress.ToString().ToLowerInvariant()})";
        var paramDecls = string.Join(", ", m.ParamTypeFQNs.Select((t, i) => $"{t} p{i}"));

        if (m.ReturnStyle == ReturnStyle.Voids)
        {
            AppendLine(sb, $"    public void {m.Name}({paramDecls})");
            AppendLine(sb, "    {");
            AppendLine(sb, "        var w = new ArrayBufferWriter<byte>();");
            AppendLine(sb, $"        WriteHeader(w, 3, 0, 0x{m.Hash:X16}UL);");
            AppendWriteParams(sb, m, "        ", "w");
            AppendLine(sb, $"        SendNotification(w, {opts});");
            AppendLine(sb, "    }");
            return;
        }

        var retType = m.InnerTypeFQN;
        var asyncRet = m.ReturnStyle switch
        {
            ReturnStyle.TaskOfT => $"Task<{retType}>",
            ReturnStyle.ValueTaskOfT => $"ValueTask<{retType}>",
            ReturnStyle.ValueTask => "ValueTask",
            _ => "Task",
        };

        var userCt = m.HasCancellationToken ? $"p{m.ParamTypeFQNs.Length - 1}" : "default";

        AppendLine(sb, $"    public async {asyncRet} {m.Name}({paramDecls})");
        AppendLine(sb, "    {");
        AppendLine(sb, "        var seq = AllocSeq();");
        AppendLine(sb, "        var w = new ArrayBufferWriter<byte>();");
        AppendLine(sb, $"        WriteHeader(w, 0, seq, 0x{m.Hash:X16}UL);");
        AppendWriteParams(sb, m, "        ", "w");
        AppendLine(sb, "        try");
        AppendLine(sb, "        {");

        if (retType is not null)
        {
            AppendLine(
                sb,
                $"            var _response = await SendRequestAsync(seq, w, {opts}, {m.TimeoutMs}, {userCt});"
            );
            AppendLine(
                sb,
                $"            return MemoryPackSerializer.Deserialize<{retType}>(_response);"
            );
        }
        else
        {
            AppendLine(
                sb,
                $"            await SendRequestAsync(seq, w, {opts}, {m.TimeoutMs}, {userCt});"
            );
        }

        AppendLine(sb, "        }");
        AppendLine(sb, "        finally");
        AppendLine(sb, "        {");
        AppendLine(sb, "            CompleteRequest(seq);");
        AppendLine(sb, "        }");
        AppendLine(sb, "    }");
    }

    static void AppendWriteParams(
        StringBuilder sb,
        RpcMethodModel m,
        string indent,
        string writerVar
    )
    {
        var serialCount = m.ParamTypeFQNs.Length - (m.HasCancellationToken ? 1 : 0);
        if (serialCount == 0)
            return;
        if (serialCount == 1)
            AppendLine(sb, $"{indent}MemoryPackSerializer.Serialize({writerVar}, p0);");
        else
        {
            var indices = m.HasCancellationToken
                ? Enumerable.Range(0, m.ParamTypeFQNs.Length - 1)
                : Enumerable.Range(0, m.ParamTypeFQNs.Length);
            var tuple = string.Join(", ", indices.Select(x => $"p{x}"));
            AppendLine(sb, $"{indent}MemoryPackSerializer.Serialize({writerVar}, ({tuple}));");
        }
    }

    // ── Dispatcher ────────────────────────────────────────────

    static void AppendDispatcher(StringBuilder sb, RpcInterfaceModel model)
    {
        var dn = StripI(model.Name) + "Dispatcher";
        var iface = model.FullyQualifiedName;

        AppendLine(
            sb,
            $$"""
file sealed class {{dn}} : RpcDispatcherBase<{{iface}}>
{
    public {{dn}}(RpcTransport transport, {{iface}} handler) : base(transport, handler) { }
"""
        );

        AppendLine(sb);
        AppendDispatchRequestAsync(sb, model);
        AppendLine(sb);
        AppendDispatchNotificationAsync(sb, model);

        AppendLine(sb, "}");
    }

    static void AppendDispatchRequestAsync(StringBuilder sb, RpcInterfaceModel model)
    {
        AppendLine(
            sb,
            "    protected override ValueTask DispatchRequestAsync(PeerId peer, int seq, ulong hash, ReadOnlyMemory<byte> payload)"
        );
        AppendLine(sb, "    {");
        AppendLine(sb, "        switch (hash)");
        AppendLine(sb, "        {");

        bool any = false;
        foreach (var m in model.Methods)
        {
            if (m.ReturnStyle == ReturnStyle.Voids)
                continue;
            any = true;
            AppendRequestCase(sb, m);
        }

        if (!any)
            AppendLine(sb, "            default: break;");

        AppendLine(sb, "        }");
        AppendLine(sb, "        return ValueTask.CompletedTask;");
        AppendLine(sb, "    }");
    }

    static void AppendRequestCase(StringBuilder sb, RpcMethodModel m)
    {
        var hasCt = m.HasCancellationToken;
        var isValueTask = m.ReturnStyle is ReturnStyle.ValueTask or ReturnStyle.ValueTaskOfT;

        AppendLine(sb, $"        case 0x{m.Hash:X16}UL:");
        AppendLine(sb, "        {");

        if (isValueTask && !hasCt)
        {
            AppendSyncFirstCase(sb, m);
        }
        else
        {
            AppendAlwaysAsyncCase(sb, m);
        }

        AppendLine(sb, "        }");
    }

    static void AppendSyncFirstCase(StringBuilder sb, RpcMethodModel m)
    {
        var opts = $"new RpcSendOptions(Channel:{m.Channel},Delivery:(DeliveryType){m.Delivery})";
        var isT = m.ReturnStyle == ReturnStyle.ValueTaskOfT;

        AppendLine(
            sb,
            $"            var _ct = BeginRequest(peer, channel:{m.Channel}, delivery:(DeliveryType){m.Delivery});"
        );
        AppendReadParams(sb, m, "            ");
        var args = string.Join(
            ", ",
            Enumerable.Range(0, m.ParamTypeFQNs.Length).Select(i => $"p{i}")
        );
        var resultVar = isT ? "_result" : null;

        AppendLine(sb, $"            var _vt = Handler.{m.Name}({args});");
        AppendLine(sb, "            if (_vt.IsCompletedSuccessfully)");
        AppendLine(sb, "            {");
        if (isT)
            AppendLine(sb, "                var _result = _vt.Result;");
        AppendResponseBlock(sb, m, resultVar, "                ");
        AppendLine(sb, $"                return SendResponseAsync(peer, _w, {opts});");
        AppendLine(sb, "            }");
        AppendLine(sb);
        AppendLine(sb, "            return AwaitAndRespond();");
        AppendLine(sb, $"            async ValueTask AwaitAndRespond()");
        AppendLine(sb, "            {");
        if (isT)
            AppendLine(sb, "                var _result = await _vt.Preserve();");
        else
            AppendLine(sb, "                await _vt.Preserve();");
        AppendResponseBlock(sb, m, resultVar, "                ");
        AppendLine(sb, $"                await SendResponseAsync(peer, _w, {opts});");
        AppendLine(sb, "            }");
    }

    static void AppendAlwaysAsyncCase(StringBuilder sb, RpcMethodModel m)
    {
        var opts = $"new RpcSendOptions(Channel:{m.Channel},Delivery:(DeliveryType){m.Delivery})";
        var hasCt = m.HasCancellationToken;
        var isT = m.ReturnStyle is ReturnStyle.TaskOfT or ReturnStyle.ValueTaskOfT;
        var resultVar = isT ? "_result" : null;

        AppendLine(
            sb,
            $"            var _ct = BeginRequest(peer, seq, channel:{m.Channel}, delivery:(DeliveryType){m.Delivery}, hasCancellationToken:{hasCt.ToString().ToLowerInvariant()});"
        );
        AppendReadParams(sb, m, "            ");
        var handlerArgs = hasCt
            ? NonCtArgs(m, "_ct")
            : string.Join(", ", Enumerable.Range(0, m.ParamTypeFQNs.Length).Select(i => $"p{i}"));

        AppendLine(sb, "            return AwaitAndRespond();");
        AppendLine(sb, $"            async ValueTask AwaitAndRespond()");
        AppendLine(sb, "            {");
        if (isT)
            AppendLine(sb, $"                var _result = await Handler.{m.Name}({handlerArgs});");
        else
            AppendLine(sb, $"                await Handler.{m.Name}({handlerArgs});");
        AppendResponseBlock(sb, m, resultVar, "                ");
        AppendLine(sb, $"                await SendResponseAsync(peer, _w, {opts});");
        AppendLine(sb, "            }");
    }

    static void AppendResponseBlock(
        StringBuilder sb,
        RpcMethodModel m,
        string? resultVar,
        string indent
    )
    {
        var isT = m.ReturnStyle is ReturnStyle.TaskOfT or ReturnStyle.ValueTaskOfT;
        AppendLine(sb, $"{indent}var _w = new ArrayBufferWriter<byte>();");
        AppendLine(sb, $"{indent}WriteResponseHeader(_w, seq);");
        if (isT && resultVar is not null)
            AppendLine(sb, $"{indent}MemoryPackSerializer.Serialize(_w, {resultVar});");
    }

    static string NonCtArgs(RpcMethodModel m, string ctExpr)
    {
        var nonCtCount = m.ParamTypeFQNs.Length - 1;
        if (nonCtCount == 0)
            return ctExpr;
        var dataArgs = string.Join(", ", Enumerable.Range(0, nonCtCount).Select(i => $"p{i}"));
        return $"{dataArgs}, {ctExpr}";
    }

    static void AppendDispatchNotificationAsync(StringBuilder sb, RpcInterfaceModel model)
    {
        AppendLine(
            sb,
            "    protected override void DispatchNotification(PeerId peer, ulong hash, ReadOnlyMemory<byte> payload)"
        );
        AppendLine(sb, "    {");
        AppendLine(sb, "        switch (hash)");
        AppendLine(sb, "        {");

        bool any = false;
        foreach (var m in model.Methods)
        {
            if (m.ReturnStyle != ReturnStyle.Voids)
                continue;
            any = true;
            AppendLine(sb, $"        case 0x{m.Hash:X16}UL:");
            AppendLine(sb, "        {");
            AppendLine(
                sb,
                $"            BeginNotification(peer, channel:{m.Channel}, delivery:(DeliveryType){m.Delivery});"
            );
            AppendReadParams(sb, m, "            ");
            var args = string.Join(
                ", ",
                Enumerable.Range(0, m.ParamTypeFQNs.Length).Select(i => $"p{i}")
            );
            AppendLine(sb, $"            Handler.{m.Name}({args});");
            AppendLine(sb, "            break;");
            AppendLine(sb, "        }");
        }

        if (!any)
            AppendLine(sb, "            default: break;");

        AppendLine(sb, "        }");
        AppendLine(sb, "    }");
    }

    static void AppendReadParams(StringBuilder sb, RpcMethodModel m, string indent)
    {
        var serialCount = m.ParamTypeFQNs.Length - (m.HasCancellationToken ? 1 : 0);
        if (serialCount == 0)
            return;
        if (serialCount == 1)
        {
            AppendLine(
                sb,
                $"{indent}var p0 = MemoryPackSerializer.Deserialize<{m.ParamTypeFQNs[0]}>(payload.Span);"
            );
        }
        else
        {
            var types = string.Join(", ", m.ParamTypeFQNs.Take(serialCount));
            var names = string.Join(", ", Enumerable.Range(0, serialCount).Select(x => $"p{x}"));
            AppendLine(
                sb,
                $"{indent}var ({names}) = MemoryPackSerializer.Deserialize<({types})>(payload.Span);"
            );
        }
    }

    static void AppendRegistration(StringBuilder sb, RpcInterfaceModel model)
    {
        var rn = StripI(model.Name) + "Registration";
        var pn = StripI(model.Name) + "Proxy";
        var dn = StripI(model.Name) + "Dispatcher";
        var iface = model.FullyQualifiedName;

        AppendLine(
            sb,
            $$"""
file static class {{rn}}
{
    [ModuleInitializer]
    internal static void Register()
    {
        global::GoodRpc.RpcRegistry.RegisterProxy<{{iface}}>((t, p) => new {{pn}}(t, p));
        global::GoodRpc.RpcRegistry.RegisterDispatcher<{{iface}}>((t, h) => new {{dn}}(t, h));
    }
}
"""
        );
    }
}
