using System.Text;

namespace GoodRpc.SourceGen;

internal static class Emitter
{
    public static string Generate(RpcInterfaceModel model)
    {
        var sb = new StringBuilder();
        sb.Append(Header);

        AppendProxy(sb, model);
        sb.AppendLine();
        AppendDispatcher(sb, model);
        sb.AppendLine();
        AppendRegistration(sb, model);

        return sb.ToString();
    }

    static void Append(StringBuilder sb, string text) => sb.Append(text);

    static void AppendLine(StringBuilder sb, string text = "") => sb.AppendLine(text);

    static void AppendLine(StringBuilder sb, string prefix, string text) =>
        sb.AppendLine(prefix + text);

    static string StripI(string name) =>
        name.StartsWith("I") && name.Length > 1 && char.IsUpper(name[1]) ? name.Substring(1) : name;

    static readonly string Header = $$"""
// <auto-generated/>
#pragma warning disable

using System;
using System.Buffers;
using System.Buffers.Binary;
using System.Collections.Concurrent;
using System.Runtime.CompilerServices;
using System.Threading;
using System.Threading.Tasks;
using MemoryPack;
using GoodRpc;

""";

    static void AppendProxy(StringBuilder sb, RpcInterfaceModel model)
    {
        var pn = StripI(model.Name) + "Proxy";
        var iface = model.FullyQualifiedName;

        AppendLine(
            sb,
            $$"""
file sealed class {{pn}} : {{iface}}, IDisposable, IAsyncDisposable
{
    private readonly RpcTransport _transport;
    private readonly PeerId _peer;
    private readonly IDisposable _subscription;
    private int _nextSeq;
    private readonly ConcurrentDictionary<int, Pending> _pending = new();

    private readonly record struct Pending(TaskCompletionSource<byte[]> TCS, CancellationTokenSource CTS, CancellationTokenRegistration CTReg);

    public {{pn}}(RpcTransport transport, PeerId peer)
    {
        _transport = transport; _peer = peer;
        _subscription = transport.Subscribe(peer, OnMessage);
        transport.Disconnected += OnDisconnected;
    }
"""
        );

        foreach (var m in model.Methods)
            AppendProxyMethod(sb, m);

        AppendLine(sb, ProxyOnMessage);
        AppendLine(sb, ProxyOnDisconnected);
        AppendLine(sb, ProxyErrorHelper);
        AppendLine(sb, ProxyDispose);
        AppendLine(sb, "}");
    }

    static void AppendProxyMethod(StringBuilder sb, RpcMethodModel m)
    {
        var opts =
            $"new RpcSendOptions(Channel:{m.Channel},Delivery:(DeliveryType){m.Delivery},TimeoutMs:{m.TimeoutMs},Compress:{m.Compress.ToString().ToLowerInvariant()})";
        var paramDecls = string.Join(", ", m.ParamTypeFQNs.Select((t, i) => $"{t} p{i}"));

        if (m.ReturnStyle == ReturnStyle.Voids)
        {
            AppendLine(sb, $"    public void {m.Name}({paramDecls})");
            AppendLine(sb, "    {");
            AppendWriteHeader(sb, 3, 0, m.Hash, "        ");
            AppendWriteParams(sb, m, "        ");
            AppendLine(
                sb,
                $"        _ = _transport.SendAsync(_peer, _writer.WrittenMemory, {opts});"
            );
            AppendLine(sb, "    }");
        }
        else
        {
            var retType = m.InnerTypeFQN;
            var asyncRet = m.ReturnStyle switch
            {
                ReturnStyle.TaskOfT => $"Task<{retType}>",
                ReturnStyle.ValueTaskOfT => $"ValueTask<{retType}>",
                ReturnStyle.ValueTask => "ValueTask",
                _ => "Task",
            };

            AppendLine(sb, $"    public async {asyncRet} {m.Name}({paramDecls})");
            AppendLine(sb, "    {");
            AppendLine(sb, "        var seq = Interlocked.Increment(ref _nextSeq);");
            AppendLine(
                sb,
                "        var tcs = new TaskCompletionSource<byte[]>(TaskCreationOptions.RunContinuationsAsynchronously);"
            );

            if (m.TimeoutMs > 0)
            {
                AppendLine(
                    sb,
                    $"        using var cts = new CancellationTokenSource({m.TimeoutMs});"
                );
                AppendLine(
                    sb,
                    "        cts.Token.Register(() => { if (_pending.TryRemove(seq, out var c)) c.TCS.TrySetException(new RpcTimeoutException()); });"
                );
            }
            else
                AppendLine(sb, "        using var cts = new CancellationTokenSource();");

            AppendLine(sb, "        _pending[seq] = new Pending(tcs, cts, default);");
            AppendCancellationTokenRegistration(sb, m);
            AppendLine(sb, "        try");
            AppendLine(sb, "        {");
            AppendWriteHeader(sb, 0, "seq", m.Hash, "            ");
            AppendWriteParams(sb, m, "            ");
            AppendLine(
                sb,
                $"            await _transport.SendAsync(_peer, _writer.WrittenMemory, {opts});"
            );
            AppendLine(sb, "            var response = await tcs.Task;");
            if (retType is not null)
                AppendLine(
                    sb,
                    $"            return MemoryPackSerializer.Deserialize<{retType}>(response);"
                );
            AppendLine(sb, "        }");
            AppendLine(sb, "        finally");
            AppendLine(sb, "        {");
            AppendLine(sb, "            if (_pending.TryRemove(seq, out var p))");
            AppendLine(sb, "            {");
            AppendLine(sb, "                p.CTReg.Dispose();");
            AppendLine(sb, "            }");
            AppendLine(sb, "            cts.Cancel();");
            AppendLine(sb, "        }");
            AppendLine(sb, "    }");
        }
    }

    static void AppendWriteHeader(StringBuilder sb, byte type, int seq, ulong hash, string i) =>
        AppendWriteHeader(sb, type, seq.ToString(), hash, i);

    static void AppendWriteHeader(StringBuilder sb, byte type, string seqExpr, ulong hash, string i)
    {
        AppendLine(sb, i, "var _writer = new ArrayBufferWriter<byte>();");
        AppendLine(sb, i, "var _s = _writer.GetSpan(13);");
        AppendLine(sb, i, $"_s[0] = {type};");
        AppendLine(sb, i, $"BinaryPrimitives.WriteInt32LittleEndian(_s.Slice(1), {seqExpr});");
        AppendLine(
            sb,
            i,
            $"BinaryPrimitives.WriteUInt64LittleEndian(_s.Slice(5), 0x{hash:X16}UL);"
        );
        AppendLine(sb, i, "_writer.Advance(13);");
    }

    static void AppendWriteParams(StringBuilder sb, RpcMethodModel m, string i)
    {
        var serialCount = m.ParamTypeFQNs.Length - (m.HasCancellationToken ? 1 : 0);
        if (serialCount == 0)
            return;
        if (serialCount == 1)
            AppendLine(sb, i, "MemoryPackSerializer.Serialize(_writer, p0);");
        else
        {
            var indices = m.HasCancellationToken
                ? Enumerable.Range(0, m.ParamTypeFQNs.Length - 1)
                : Enumerable.Range(0, m.ParamTypeFQNs.Length);
            var tuple = string.Join(", ", indices.Select(x => $"p{x}"));
            AppendLine(sb, i, $"MemoryPackSerializer.Serialize(_writer, ({tuple}));");
        }
    }

    static void AppendCancellationTokenRegistration(StringBuilder sb, RpcMethodModel m)
    {
        if (!m.HasCancellationToken)
            return;

        var ctParam = $"p{m.ParamTypeFQNs.Length - 1}";
        AppendLine(sb, "        CancellationTokenRegistration ctReg = default;");
        AppendLine(sb, $$"""        if ({{ctParam}}.CanBeCanceled)""");
        AppendLine(sb, "        {");
        AppendLine(sb, $$"""            ctReg = {{ctParam}}.Register(s =>""");
        AppendLine(sb, "            {");
        AppendLine(sb, "                var seqId = (int)s!;");
        AppendLine(sb, "                if (_pending.TryRemove(seqId, out var c))");
        AppendLine(sb, "                {");
        AppendLine(sb, "                    var w = new ArrayBufferWriter<byte>();");
        AppendLine(sb, "                    var sp = w.GetSpan(5); sp[0] = 6;");
        AppendLine(
            sb,
            "                    BinaryPrimitives.WriteInt32LittleEndian(sp.Slice(1), seqId);"
        );
        AppendLine(sb, "                    w.Advance(5);");
        AppendLine(
            sb,
            "                    _ = _transport.SendAsync(_peer, w.WrittenMemory, new RpcSendOptions());"
        );
        AppendLine(sb, "                    c.TCS.TrySetCanceled(c.CTS.Token);");
        AppendLine(sb, "                }");
        AppendLine(sb, "            }, seq);");
        AppendLine(sb, "            _pending[seq] = new Pending(tcs, cts, ctReg);");
        AppendLine(sb, "        }");
    }

    static readonly string ProxyOnMessage = $$"""
    private void OnMessage(RpcMessage msg)
    {
        var span = msg.Payload.Span;
        if (span.Length < 5) return;
        var type = span[0];
        if (type != 1 && type != 2) return;
        var seq = BinaryPrimitives.ReadInt32LittleEndian(span.Slice(1));
        if (!_pending.TryGetValue(seq, out var call)) return;
        var payload = span.Slice(5).ToArray();
        if (type == 1) call.TCS.TrySetResult(payload);
        else call.TCS.TrySetException(CreateErrorException(payload));
    }
""";

    static readonly string ProxyOnDisconnected = $$"""
    private void OnDisconnected(PeerId peer)
    {
        if (peer.Equals(_peer))
            foreach (var (_, c) in _pending) { c.TCS.TrySetException(new RpcDisconnectedException()); }
    }
""";

    static readonly string ProxyErrorHelper = $$"""
    private static RpcException CreateErrorException(byte[] payload)
    {
        try { var err = MemoryPackSerializer.Deserialize<RpcError>(payload); return new RpcException(err.Code, err.Message); }
        catch { return new RpcException(RpcErrorCode.Unknown); }
    }
""";

    static readonly string ProxyDispose = $$"""
    public void Dispose()
    {
        _subscription.Dispose();
        _transport.Disconnected -= OnDisconnected;
        foreach (var (_, c) in _pending) { c.TCS.TrySetException(new RpcDisconnectedException()); c.CTReg.Dispose(); c.CTS.Cancel(); c.CTS.Dispose(); }
        _pending.Clear();
    }
    public ValueTask DisposeAsync() { Dispose(); return ValueTask.CompletedTask; }
""";

    static void AppendDispatcher(StringBuilder sb, RpcInterfaceModel model)
    {
        var dn = StripI(model.Name) + "Dispatcher";
        var iface = model.FullyQualifiedName;

        AppendLine(
            sb,
            $$"""
file sealed class {{dn}} : IDisposable, IAsyncDisposable
{
    private readonly RpcTransport _transport;
    private readonly {{iface}} _handler;
    private readonly IDisposable _subscription;
    private readonly ConcurrentDictionary<PeerId, CancellationTokenSource> _peerCts = new();
    private readonly ConcurrentDictionary<(PeerId Peer, int Seq), CancellationTokenSource> _inFlight = new();

    public {{dn}}(RpcTransport transport, {{iface}} handler)
    {
        _transport = transport; _handler = handler;
        _subscription = transport.SubscribeAll(OnMessage);
        transport.Disconnected += OnDisconnected;
    }
"""
        );

        AppendLine(sb, DispatcherOnMessage);
        sb.AppendLine();
        AppendDispatcherHandleRequest(sb, model);
        sb.AppendLine();
        AppendDispatcherHandleNotification(sb, model);
        sb.AppendLine();

        AppendLine(sb, DispatcherOnDisconnected);
        AppendLine(sb);
        AppendLine(sb, DispatcherDispose);
        AppendLine(sb, "}");
    }

    static readonly string DispatcherOnMessage = $$"""
    private void OnMessage(RpcMessage msg)
    {
        var span = msg.Payload.Span;
        if (span.Length < 1) return;
        var type = span[0];
        if (type == 0)
        {
            if (span.Length < 13) return;
            var seq = BinaryPrimitives.ReadInt32LittleEndian(span.Slice(1));
            var hash = BinaryPrimitives.ReadUInt64LittleEndian(span.Slice(5));
            var payload = msg.Payload.Slice(13);
            _ = HandleRequestAsync(msg.Peer, seq, hash, payload);
        }
        else if (type == 3)
        {
            if (span.Length < 13) return;
            var hash = BinaryPrimitives.ReadUInt64LittleEndian(span.Slice(5));
            var payload = msg.Payload.Slice(13);
            _ = HandleNotificationAsync(hash, payload);
        }
        else if (type == 6)
        {
            if (span.Length < 5) return;
            var cancelSeq = BinaryPrimitives.ReadInt32LittleEndian(span.Slice(1));
            if (_inFlight.TryGetValue((msg.Peer, cancelSeq), out var cancelCts))
                cancelCts.Cancel();
        }
    }
""";

    static void AppendDispatcherHandleRequest(StringBuilder sb, RpcInterfaceModel model)
    {
        AppendLine(
            sb,
            $$"""
    private async Task HandleRequestAsync(PeerId peer, int seq, ulong hash, ReadOnlyMemory<byte> payload)
    {
        var peerCts = _peerCts.GetOrAdd(peer, _ => new CancellationTokenSource());
        RpcContext.CurrentPeer = peer;
        try { switch (hash) {
"""
        );

        foreach (var m in model.Methods)
        {
            if (m.ReturnStyle == ReturnStyle.Voids)
                continue;
            AppendRequestCase(sb, m);
        }

        AppendLine(sb, "        default: break;");
        AppendLine(sb, """        } }""");
        AppendLine(sb, """        catch (OperationCanceledException) { }""");
        AppendLine(
            sb,
            """        catch (Exception) { try { await SendError(peer, seq, RpcErrorCode.HandlerException); } catch { } }"""
        );
        AppendLine(
            sb,
            """        finally { _inFlight.TryRemove((peer, seq), out _); RpcContext.Reset(); }"""
        );
        AppendLine(sb, "    }");
        AppendLine(sb);
        AppendLine(sb, DispatcherSendError);
    }

    static void AppendRequestCase(StringBuilder sb, RpcMethodModel m)
    {
        AppendLine(sb, $"        case 0x{m.Hash:X16}UL:");
        AppendLine(sb, "        {");
        AppendLine(sb, $"            RpcContext.CurrentChannel = {m.Channel};");
        AppendLine(sb, $"            RpcContext.CurrentDelivery = (DeliveryType){m.Delivery};");

        if (m.HasCancellationToken)
        {
            AppendLine(
                sb,
                "            using var requestCts = CancellationTokenSource.CreateLinkedTokenSource(peerCts.Token);"
            );
            AppendLine(sb, "            _inFlight[(peer, seq)] = requestCts;");
            AppendLine(sb, "            RpcContext.CurrentCancellation = requestCts.Token;");
        }
        else
        {
            AppendLine(sb, "            RpcContext.CurrentCancellation = peerCts.Token;");
        }

        AppendReadParams(sb, m, "            ");
        var args = m.HasCancellationToken
            ? NonCtArgs(m, "requestCts.Token")
            : string.Join(", ", Enumerable.Range(0, m.ParamTypeFQNs.Length).Select(i => $"p{i}"));

        if (m.ReturnStyle == ReturnStyle.Task || m.ReturnStyle == ReturnStyle.ValueTask)
            AppendLine(sb, $"            await _handler.{m.Name}({args});");
        else
            AppendLine(sb, $"            var _result = await _handler.{m.Name}({args});");

        AppendLine(
            sb,
            "            { var w = new ArrayBufferWriter<byte>(); var s = w.GetSpan(5); s[0]=1;"
        );
        AppendLine(
            sb,
            "            BinaryPrimitives.WriteInt32LittleEndian(s.Slice(1), seq); w.Advance(5);"
        );
        if (m.ReturnStyle == ReturnStyle.TaskOfT || m.ReturnStyle == ReturnStyle.ValueTaskOfT)
            AppendLine(sb, "            MemoryPackSerializer.Serialize(w, _result);");
        AppendLine(
            sb,
            $"            await _transport.SendAsync(peer, w.WrittenMemory, new RpcSendOptions(Channel:{m.Channel},Delivery:(DeliveryType){m.Delivery})); }}"
        );
        AppendLine(sb, "            break;");
        AppendLine(sb, "        }");
    }

    static string NonCtArgs(RpcMethodModel m, string ctExpr)
    {
        var nonCtCount = m.ParamTypeFQNs.Length - 1;
        if (nonCtCount == 0)
            return ctExpr;
        var dataArgs = string.Join(", ", Enumerable.Range(0, nonCtCount).Select(i => $"p{i}"));
        return $"{dataArgs}, {ctExpr}";
    }

    static readonly string DispatcherSendError = $$"""
    private async Task SendError(PeerId peer, int seq, RpcErrorCode code)
    {
        var w = new ArrayBufferWriter<byte>(); var s = w.GetSpan(5); s[0]=2;
        BinaryPrimitives.WriteInt32LittleEndian(s.Slice(1), seq); w.Advance(5);
        MemoryPackSerializer.Serialize(w, new RpcError(code));
        await _transport.SendAsync(peer, w.WrittenMemory, new RpcSendOptions());
    }
""";

    static void AppendDispatcherHandleNotification(StringBuilder sb, RpcInterfaceModel model)
    {
        AppendLine(
            sb,
            """    private async Task HandleNotificationAsync(ulong hash, ReadOnlyMemory<byte> payload)"""
        );
        AppendLine(sb, "    {");
        AppendLine(sb, "        try { switch (hash) {");

        bool any = false;
        foreach (var m in model.Methods)
        {
            if (m.ReturnStyle != ReturnStyle.Voids)
                continue;
            any = true;
            AppendLine(sb, $"        case 0x{m.Hash:X16}UL:");
            AppendLine(sb, "        {");
            AppendLine(sb, $"            RpcContext.CurrentChannel = {m.Channel};");
            AppendLine(sb, $"            RpcContext.CurrentDelivery = (DeliveryType){m.Delivery};");
            AppendReadParams(sb, m, "            ");
            var args = string.Join(
                ", ",
                Enumerable.Range(0, m.ParamTypeFQNs.Length).Select(i => $"p{i}")
            );
            AppendLine(sb, $"            _handler.{m.Name}({args});");
            AppendLine(sb, "            break;");
            AppendLine(sb, "        }");
        }
        if (!any)
            AppendLine(sb, "        default: break;");

        AppendLine(sb, "        } } catch { }");
        AppendLine(sb, "    }");
    }

    static readonly string DispatcherOnDisconnected = $$"""
    private void OnDisconnected(PeerId peer)
    { if (_peerCts.TryRemove(peer, out var cts)) { cts.Cancel(); } }
""";

    static readonly string DispatcherDispose = $$"""
    public void Dispose()
    {
        _subscription.Dispose(); _transport.Disconnected -= OnDisconnected;
        foreach (var (_, cts) in _peerCts) cts.Cancel();
        _peerCts.Clear();
        _inFlight.Clear();
    }
    public ValueTask DisposeAsync() { Dispose(); return ValueTask.CompletedTask; }
""";

    static void AppendReadParams(StringBuilder sb, RpcMethodModel m, string i)
    {
        var serialCount = m.ParamTypeFQNs.Length - (m.HasCancellationToken ? 1 : 0);
        if (serialCount == 0)
            return;
        if (serialCount == 1)
        {
            AppendLine(
                sb,
                i,
                $"var p0 = MemoryPackSerializer.Deserialize<{m.ParamTypeFQNs[0]}>(payload.Span);"
            );
        }
        else
        {
            var types = string.Join(", ", m.ParamTypeFQNs.Take(serialCount));
            var names = string.Join(", ", Enumerable.Range(0, serialCount).Select(x => $"p{x}"));
            AppendLine(
                sb,
                i,
                $"var ({names}) = MemoryPackSerializer.Deserialize<({types})>(payload.Span);"
            );
        }
    }

    static void AppendRegistration(StringBuilder sb, RpcInterfaceModel model)
    {
        var rn = StripI(model.Name) + "Registration";
        var pn = StripI(model.Name) + "Proxy";
        var dn = StripI(model.Name) + "Dispatcher";
        var iface = model.FullyQualifiedName;

        AppendLine(
            sb,
            $$"""
file static class {{rn}}
{
    [ModuleInitializer]
    internal static void Register()
    {
        global::GoodRpc.RpcRegistry.RegisterProxy<{{iface}}>((t, p) => new {{pn}}(t, p));
        global::GoodRpc.RpcRegistry.RegisterDispatcher<{{iface}}>((t, h) => new {{dn}}(t, h));
    }
}
"""
        );
    }
}
